### PR TITLE
[WIP] Add connection pool wrap vs with benchmark

### PR DESCRIPTION
**Pull request by ysv**
**Related to** https://github.com/mperham/connection_pool/issues/120

Benchmark results On my machine (OSX 10.15.7 on 2,2 GHz 6-Core Intel Core i7)
image

image

Conclusion using `wrap` is ~7% slower than block variant with `with` method. 
As for me it doesn't have high impact on performance but still worth mentioning.

If you agree with benchmark results and my conclusion I will add the point in the [readme NOTES section](https://github.com/mperham/connection_pool#notes)

### CODE REVIEW

**Comment by ysv** [comment]
@mperham Could you please comment on this ?

**Comment by mperham** [comment]
Great info to have, thanks. Please don’t touch the gemspec, use stdlib only.

**Comment by mperham** [comment]
Can you fix the gemspec so I can merge?

**Comment by ysv** [comment]
Sure I will finalize withing the next week

**Comment by BuonOmo** [comment]
@mperham out of curiosity, what drawback do you see on adding a lib with `add_development_dependency` in a gemspec ?

**Comment by mperham** [comment]
It's code for one example benchmark. That's not important enough to justify entry in the gemspec. I think it should look more like:

```ruby
begin
  gem "benchmark-ips"
  require "benchmark/ips"
rescue LoadError
  puts "Please run `gem install benchmark-ips` before running benchmarks"
end
```

**Pull request closed without merging**
