### PR TITLE
mperham/connection_pool#113 expose pool from Wrapper

### PR DESCRIPTION
**Pull request by ook**
Expose `pool` from `ConnectionPool::Wrapper`

See #113

### CODE REVIEW

**Comment by mperham** [comment]
I'd like the method to be a little more explicit, maybe `wrapped_pool`?

**Comment by mperham** [comment]
And can you add an access in the test suite to exercise it?

**Comment by ook** [comment]
Hi @mperham thank you for your interest. I changed the method name as requested. What do you mean by "adding an access in the test suite"? I added a test to check the method correctly expose the ConnectionPool, but maybe it's not sufficient?

**Comment by mperham** [comment]
Thank you!

**Comment by aliou** [comment]
Hello @mperham, do you know when this will be available in a new version of the gem ? Thanks! (also Hi @ook!)

**Pull request merged**
